# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/hashash2/bin/cmake

# The command to remove a file.
RM = /home/hashash2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hashash2/scope

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hashash2/scope

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/hashash2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/hashash2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/hashash2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /home/hashash2/scope && $(CMAKE_COMMAND) -E cmake_progress_start /home/hashash2/scope/CMakeFiles /home/hashash2/scope/nccl_scope/CMakeFiles/progress.marks
	cd /home/hashash2/scope && $(MAKE) -f CMakeFiles/Makefile2 nccl_scope/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hashash2/scope/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/hashash2/scope && $(MAKE) -f CMakeFiles/Makefile2 nccl_scope/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/hashash2/scope && $(MAKE) -f CMakeFiles/Makefile2 nccl_scope/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/hashash2/scope && $(MAKE) -f CMakeFiles/Makefile2 nccl_scope/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/hashash2/scope && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
nccl_scope/CMakeFiles/nccl_scope.dir/rule:
	cd /home/hashash2/scope && $(MAKE) -f CMakeFiles/Makefile2 nccl_scope/CMakeFiles/nccl_scope.dir/rule
.PHONY : nccl_scope/CMakeFiles/nccl_scope.dir/rule

# Convenience name for target.
nccl_scope: nccl_scope/CMakeFiles/nccl_scope.dir/rule

.PHONY : nccl_scope

# fast build rule for target.
nccl_scope/fast:
	cd /home/hashash2/scope && $(MAKE) -f nccl_scope/CMakeFiles/nccl_scope.dir/build.make nccl_scope/CMakeFiles/nccl_scope.dir/build
.PHONY : nccl_scope/fast

src/SingleProcess/allGather.o: src/SingleProcess/allGather.cpp.o

.PHONY : src/SingleProcess/allGather.o

# target to build an object file
src/SingleProcess/allGather.cpp.o:
	cd /home/hashash2/scope && $(MAKE) -f nccl_scope/CMakeFiles/nccl_scope.dir/build.make nccl_scope/CMakeFiles/nccl_scope.dir/src/SingleProcess/allGather.cpp.o
.PHONY : src/SingleProcess/allGather.cpp.o

src/SingleProcess/allGather.i: src/SingleProcess/allGather.cpp.i

.PHONY : src/SingleProcess/allGather.i

# target to preprocess a source file
src/SingleProcess/allGather.cpp.i:
	cd /home/hashash2/scope && $(MAKE) -f nccl_scope/CMakeFiles/nccl_scope.dir/build.make nccl_scope/CMakeFiles/nccl_scope.dir/src/SingleProcess/allGather.cpp.i
.PHONY : src/SingleProcess/allGather.cpp.i

src/SingleProcess/allGather.s: src/SingleProcess/allGather.cpp.s

.PHONY : src/SingleProcess/allGather.s

# target to generate assembly for a file
src/SingleProcess/allGather.cpp.s:
	cd /home/hashash2/scope && $(MAKE) -f nccl_scope/CMakeFiles/nccl_scope.dir/build.make nccl_scope/CMakeFiles/nccl_scope.dir/src/SingleProcess/allGather.cpp.s
.PHONY : src/SingleProcess/allGather.cpp.s

src/SingleProcess/allReduce.o: src/SingleProcess/allReduce.cpp.o

.PHONY : src/SingleProcess/allReduce.o

# target to build an object file
src/SingleProcess/allReduce.cpp.o:
	cd /home/hashash2/scope && $(MAKE) -f nccl_scope/CMakeFiles/nccl_scope.dir/build.make nccl_scope/CMakeFiles/nccl_scope.dir/src/SingleProcess/allReduce.cpp.o
.PHONY : src/SingleProcess/allReduce.cpp.o

src/SingleProcess/allReduce.i: src/SingleProcess/allReduce.cpp.i

.PHONY : src/SingleProcess/allReduce.i

# target to preprocess a source file
src/SingleProcess/allReduce.cpp.i:
	cd /home/hashash2/scope && $(MAKE) -f nccl_scope/CMakeFiles/nccl_scope.dir/build.make nccl_scope/CMakeFiles/nccl_scope.dir/src/SingleProcess/allReduce.cpp.i
.PHONY : src/SingleProcess/allReduce.cpp.i

src/SingleProcess/allReduce.s: src/SingleProcess/allReduce.cpp.s

.PHONY : src/SingleProcess/allReduce.s

# target to generate assembly for a file
src/SingleProcess/allReduce.cpp.s:
	cd /home/hashash2/scope && $(MAKE) -f nccl_scope/CMakeFiles/nccl_scope.dir/build.make nccl_scope/CMakeFiles/nccl_scope.dir/src/SingleProcess/allReduce.cpp.s
.PHONY : src/SingleProcess/allReduce.cpp.s

src/SingleProcess/reduceScatter.o: src/SingleProcess/reduceScatter.cpp.o

.PHONY : src/SingleProcess/reduceScatter.o

# target to build an object file
src/SingleProcess/reduceScatter.cpp.o:
	cd /home/hashash2/scope && $(MAKE) -f nccl_scope/CMakeFiles/nccl_scope.dir/build.make nccl_scope/CMakeFiles/nccl_scope.dir/src/SingleProcess/reduceScatter.cpp.o
.PHONY : src/SingleProcess/reduceScatter.cpp.o

src/SingleProcess/reduceScatter.i: src/SingleProcess/reduceScatter.cpp.i

.PHONY : src/SingleProcess/reduceScatter.i

# target to preprocess a source file
src/SingleProcess/reduceScatter.cpp.i:
	cd /home/hashash2/scope && $(MAKE) -f nccl_scope/CMakeFiles/nccl_scope.dir/build.make nccl_scope/CMakeFiles/nccl_scope.dir/src/SingleProcess/reduceScatter.cpp.i
.PHONY : src/SingleProcess/reduceScatter.cpp.i

src/SingleProcess/reduceScatter.s: src/SingleProcess/reduceScatter.cpp.s

.PHONY : src/SingleProcess/reduceScatter.s

# target to generate assembly for a file
src/SingleProcess/reduceScatter.cpp.s:
	cd /home/hashash2/scope && $(MAKE) -f nccl_scope/CMakeFiles/nccl_scope.dir/build.make nccl_scope/CMakeFiles/nccl_scope.dir/src/SingleProcess/reduceScatter.cpp.s
.PHONY : src/SingleProcess/reduceScatter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... nccl_scope"
	@echo "... src/SingleProcess/allGather.o"
	@echo "... src/SingleProcess/allGather.i"
	@echo "... src/SingleProcess/allGather.s"
	@echo "... src/SingleProcess/allReduce.o"
	@echo "... src/SingleProcess/allReduce.i"
	@echo "... src/SingleProcess/allReduce.s"
	@echo "... src/SingleProcess/reduceScatter.o"
	@echo "... src/SingleProcess/reduceScatter.i"
	@echo "... src/SingleProcess/reduceScatter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/hashash2/scope && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

